export const CART_ADD_RESERVATION = 'CART_ADD_RESERVATION';
export const CART_REMOVE_RESERVATION = 'CART_REMOVE_RESERVATION';
export const CART_SAVE_DELIVERY_ADDRESS = 'CART_SAVE_DELIVERY_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
export const CART_RESET = 'CART_RESET';
